In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

# Для работы с матрицами
from scipy.sparse import csr_matrix

# Матричная факторизация
from implicit.als import AlternatingLeastSquares
from implicit.nearest_neighbours import ItemItemRecommender
from implicit.nearest_neighbours import bm25_weight, tfidf_weight
    
from src.metrics import precision_at_k, recall_at_k
from src.utils import load_and_prefilter
from src.recommenders import MainRecommender

In [2]:
filepaths = ['retail_train.csv', 'product.csv', 'hh_demographic.csv']

In [3]:
load_data = {'prefilter_items': True,
             'no_popular': True,
             'num_popular': 5,
             'no_unpopular': True,
             'num_unpopular': 5,
             'no_last_sales': True,
             'months_last_sales': 12,
             'not_interesting_departments':True,
             'filtered_departments': ['MISC. TRANS.'],
             'no_profit_goods': True,
             'no_expensive_goods': True}

In [4]:
df = load_and_prefilter(filepaths, load_data)
df.head()

/home/creep/Documents/Study/4q/recommendation_systems/Les05/src/utils.py:40: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  price_df = df.groupby('item_id')['quantity', 'sales_value'].sum().reset_index()
/home/creep/Documents/Study/4q/recommendation_systems/Les05/src/utils.py:47: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  price_df = df.groupby('item_id')['quantity', 'sales_value'].sum().reset_index()

,user_id,basket_id,day,item_id,quantity,sales_value,store_id,retail_disc,trans_time,week_no,coupon_disc,coupon_match_disc
0,2375,26984851472,1,1004906,1,1.39,364,-0.60,1631,1,0.0,0.0
1,2375,26984851472,1,999994,1,0.82,364,0.00,1631,1,0.0,0.0
2,2375,26984851472,1,999994,1,0.99,364,-0.30,1631,1,0.0,0.0
3,2375,26984851472,1,999994,1,1.21,364,0.00,1631,1,0.0,0.0
4,2375,26984851472,1,8160430,1,1.50,364,-0.39,1631,1,0.0,0.0